import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
export const ROOT=process.cwd();
export const E=path.resolve('evidence');
export const APP_ROOT=path.resolve(process.env.PATTERN_FERRY_APP_ROOT||'evidence/offline-app');
export const nativeFixture=path.resolve('fixtures/native-alpha2-export.xpt');
export function xpt(notes,length=384){return Buffer.from(`<?xml version="1.0"?><lmms-project version="31" type="midiclip" creator="Original test fixture" creatorversion="1.3.0-alpha.2"><head/><midiclip type="1" name="Fixture" off="0" pos="0" len="${length}" steps="16" autoresize="0" muted="0">${notes.map(([pos,key,len,vol])=>`<note type="0" pan="0" pos="${pos}" key="${key}" len="${len}" vol="${vol}"/>`).join('')}</midiclip></lmms-project>`);}
export function smf(body,ppqn=48){const n=body.length;return Buffer.from([77,84,104,100,0,0,0,6,0,0,0,1,ppqn>>8,ppqn&255,77,84,114,107,n>>>24,(n>>>16)&255,(n>>>8)&255,n&255,...body]);}
export async function openApp({viewport={width:1440,height:1000},offline=true}={}){const browser=await chromium.launch({chromiumSandbox:true});const commands=execFileSync('ps',['-eo','pid=,ppid=,args='],{encoding:'utf8'}).split('\n').filter(line=>{const m=line.trim().match(/^(\d+)\s+(\d+)\s+(.*)$/);return m&&Number(m[2])===process.pid&&/chrome(?:-headless-shell)?(?:\s|$)/.test(m[3]);});try{assert.equal(commands.length,1,'Expected one observable Chromium main process');assert.ok(!commands[0].includes('--no-sandbox')&&!commands[0].includes('--disable-setuid-sandbox'),'Chromium sandbox must stay enabled');await fs.mkdir(E,{recursive:true});let launches=[];try{launches=JSON.parse(await fs.readFile(path.join(E,'browser-launches.json'),'utf8'));}catch(error){if(error.code!=='ENOENT')throw error;}launches.push({script:path.basename(process.argv[1]),chromiumSandbox:true,command:commands[0].trim()});await fs.writeFile(path.join(E,'browser-launches.json'),JSON.stringify(launches,null,2)+'\n');}catch(error){await browser.close();throw error;}const context=await browser.newContext({viewport,acceptDownloads:true});await context.setOffline(offline);const page=await context.newPage();const errors=[],network=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await page.goto(pathToFileURL(path.join(APP_ROOT,'index.html')).href);await page.locator('#sample').waitFor();return {browser,context,page,errors,network};}
export async function load(page,input,filename){if(typeof input==='string')await page.locator('#file-input').setInputFiles(input);else await page.locator('#file-input').setInputFiles({name:filename,mimeType:filename.endsWith('.xpt')?'application/xml':'audio/midi',buffer:input});await page.locator('#review-content').waitFor({state:'visible'});}
export async function saveDownload(page,button,filename){const destination=path.join(E,filename);await assert.rejects(fs.stat(destination),{code:'ENOENT'});const pending=page.waitForEvent('download');await page.locator(button).click();const download=await pending;await download.saveAs(destination);assert.ok((await fs.stat(destination)).size>0);return destination;}
export async function exportReview(page,filename){return saveDownload(page,'#report',filename);}
export async function exportMusic(page,filename){await page.locator('#ack').check();await assert.doesNotReject(page.locator('#download').click({trial:true}));return saveDownload(page,'#download',filename);}
