(function(){
'use strict';
const C=globalThis.PatternFerryCore,$=id=>document.getElementById(id);
let language='ja',revision=0,currentBytes=null,currentName='',plan=null,lastError=null;
const text=(ja,en)=>language==='ja'?ja:en;
const errorJa={SIZE:'ファイルは 2 MiB 以下にしてください',FORMAT:'非圧縮 XPT / MIDI を選んでください。MMP・XPTZ は対象外です',ENCODING:'XML は UTF-8 のみ対応しています',XML:'XML の構造が正しくありません',XML_META:'外部・内部 DTD と追加メタデータは対象外です',XML_LIMIT:'XML の深さ・要素数が上限を超えています',FIELD:'未対応の項目が含まれています',NUMBER:'数値の形式または範囲が正しくありません',VERSION:'LMMS alpha.2 のファイル形式 31 のみ対応しています',STEPS:'ステップ音符・ビートクリップは対象外です',TRIM:'トリム済み・長さがゼロの音符は対象外です',PAN:'音符ごとのパンは対象外です',DETUNE:'デチューン・オートメーションは対象外です',MUTED:'ミュートされたクリップは対象外です',VELOCITY:'無音または範囲外の強弱値は扱えません',PITCH:'音高が MIDI の範囲外です',OVERLAP:'同じ高さの音符が重なっています',CHANNEL:'音符トラックとチャンネルは 1 つだけにしてください',SMPTE:'SMPTE 時間形式は対象外です',SYSEX:'SysEx は対象外です',CONTROLLER:'コントローラー・音色変更・ベンドなどは対象外です',TEMPO:'途中で変化するテンポは対象外です',META:'未対応の MIDI メタデータがあります',MIDI:'MIDI の構造・音符の対応が正しくありません',MIDI_LIMIT:'MIDI イベント数が上限を超えています',RELEASE:'ノートオフの強弱は 0 のみ対応しています',BOUNDS:'時間・長さが上限を超えています',NOTES:'通常音符 1–4096 個のクリップを選んでください',ROUNDING:'48 PPQN に収まらない時刻があります。丸めを選び、誤差を確認してください',READ:'ファイルを読み込めませんでした'};
function policy(){return document.querySelector('input[name=rounding]:checked').value;}
function setLanguage(next){language=next;document.documentElement.lang=next;for(const e of document.querySelectorAll('[data-ja][data-en]'))e.textContent=e.dataset[next];$('lang-ja').setAttribute('aria-pressed',String(next==='ja'));$('lang-en').setAttribute('aria-pressed',String(next==='en'));if(plan)renderPlan(false);else if(lastError){$('error').textContent=errorMessage(lastError);$('state-badge').textContent=text('読み込み不可','Not supported');}else $('state-badge').textContent=text('ファイル待ち','Awaiting file');}
function clearResult(){plan=null;lastError=null;$('ack').checked=false;$('download').disabled=true;$('review-content').hidden=true;$('empty-state').hidden=false;$('error').hidden=true;$('error').textContent='';$('note-rows').replaceChildren();$('note-preview').replaceChildren();$('status').textContent='';$('state-badge').classList.remove('ready');$('state-badge').textContent=text('ファイル待ち','Awaiting file');}
function errorMessage(error){return text(errorJa[error.code]||'このファイルは扱えません',error.message||'This file is unsupported');}
function showError(error){lastError=error;$('error').textContent=errorMessage(error);$('error').hidden=false;$('state-badge').textContent=text('読み込み不可','Not supported');}
async function loadFile(file){const token=++revision;clearResult();currentBytes=null;currentName='';$('file-summary').hidden=true;if(!file)return;
 if(file.size>C.LIMITS.bytes){showError({code:'SIZE',message:'File exceeds 2 MiB'});return;}
 currentName=file.name;$('status').textContent=text('ファイルを確認中…','Checking the file…');
 try{const content=await file.arrayBuffer();if(token!==revision)return;currentBytes=new Uint8Array(content);analyze();}
 catch(error){if(token!==revision)return;currentBytes=null;currentName='';clearResult();showError({code:'READ',message:'Could not read this file'});}
}
function analyze(){clearResult();if(!currentBytes)return;try{plan=C.inspect(currentBytes,currentName,{rounding:policy()});$('filename').textContent=currentName;$('file-summary').hidden=false;renderPlan(true);}catch(error){showError(error);}}
function noteName(key){return ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][key%12]+(Math.floor(key/12)-1);}
function svg(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function drawPreview(){const chart=$('note-preview');chart.replaceChildren();if(!Number.isFinite(plan.clip.length)||plan.clip.length<=0||plan.clip.notes.some(n=>n.length<=0)){const message=text('この丸め結果ではプレビューできません','No valid preview for this rounded timing');const label=svg('text',{x:35,y:80,fill:'#8d3d29','font-size':14});label.textContent=message;chart.append(label);chart.setAttribute('aria-label',message);return;}const keys=plan.clip.notes.map(n=>n.key),lo=Math.min(...keys)-2,hi=Math.max(...keys)+2,range=Math.max(hi-lo+1,12);for(let i=0;i<9;i++){const x=35+i*92;chart.append(svg('line',{x1:x,y1:10,x2:x,y2:148,stroke:'#cdd8c6','stroke-width':i%2===0?1:.5}));}for(let i=0;i<7;i++){const y=12+i*22;chart.append(svg('line',{x1:35,y1:y,x2:775,y2:y,stroke:'#e0e7d9'}));}for(const n of plan.clip.notes.slice(0,128)){const x=35+n.start/plan.clip.length*740,y=12+(hi-n.key)/range*132,w=Math.max(2,n.length/plan.clip.length*740);chart.append(svg('rect',{x,y,width:w,height:Math.max(4,Math.min(12,126/range)),rx:1.7,fill:n.volume>125?'#176a5f':'#70a282'}));}const title=svg('title',{});title.textContent=text(`${plan.rows.length} 音符の出力先プレビュー`,`${plan.rows.length} destination notes`);chart.prepend(title);chart.setAttribute('aria-label',title.textContent);}
function renderPlan(resetAck){if(!plan)return;if(resetAck)$('ack').checked=false;$('empty-state').hidden=true;$('review-content').hidden=false;$('direction').textContent=plan.direction==='xpt-midi'?'XPT → MIDI':'MIDI → XPT';$('print-source').textContent=currentName+' · '+(plan.direction==='xpt-midi'?'XPT → MIDI':'MIDI → XPT');$('note-count').textContent=String(plan.rows.length);$('clip-length').textContent=String(plan.clip.length);$('change-count').textContent=String(plan.rows.filter(r=>r.startError!=='0'||r.endError!=='0'||r.velocityError!=='0').length);$('state-badge').textContent=plan.canExport?text('確認して書き出す','Review to export'):text('丸め・内容の確認が必要','Conversion blocked');$('state-badge').classList.toggle('ready',plan.canExport);$('status').textContent=text(`${plan.rows.length} 音符を解析しました。ファイルは送信していません`,`${plan.rows.length} notes analyzed. No file data was sent.`);
 const warning=$('review-warnings');warning.replaceChildren();const add=message=>{const p=document.createElement('p');p.textContent=message;warning.append(p);};add(text('強弱は LMMS 0–200 ↔ MIDI 0–127 の尺度に丸めます。往復しても元の値に戻るとは限りません','Velocity is rounded between LMMS 0–200 and MIDI 0–127. A round-trip may not restore the original value.'));add(text('楽器、パン、デチューン、プロジェクトのテンポ、音の一致は保証しません。MIDI の試聴用テンポは 120 BPM です','Instrument sound/audio equivalence is not preserved. Destination project tempo stays unchanged; MIDI audition tempo is 120 BPM.'));for(const reason of plan.blocked)add(errorMessage(reason));if(plan.requiresRounding&&policy()==='nearest')add(text('最も近い tick への丸めが選択されています。下の正確な分数の誤差を確認してください','Nearest-tick rounding is selected. Review the exact fractional errors below.'));
 $('length-review').textContent=text(`クリップ終端: 正確な値 ${plan.lengthExact} → ${plan.clip.length} tick / 誤差 ${plan.lengthError} tick`, `Clip end: exact ${plan.lengthExact} → ${plan.clip.length} ticks / error ${plan.lengthError} ticks`);
 $('context-report').textContent=JSON.stringify({source:plan.context,returnDefaults:{name:'PatternFerry',color:null,autoresize:0,steps:16,destinationPosition:'preserved',instrument:'unchanged'},metadataNotTransferred:plan.meta},null,2);
 $('velocity-label').textContent=plan.direction==='xpt-midi'?'LMMS 0–200 → MIDI 0–127':'MIDI 1–127 → LMMS 1–200';
 const rows=document.createDocumentFragment();for(const r of plan.rows){const tr=document.createElement('tr');const values=[`${noteName(r.key)} (${r.key})`,`${r.sourceStart} → ${r.targetStart}`,r.startError,`${r.sourceEnd} → ${r.targetEnd}`,r.endError,`${r.sourceVelocity} → ${r.targetVelocity}`,r.velocityError];values.forEach((v,i)=>{const td=document.createElement('td');td.textContent=v;if([2,4,6].includes(i)&&v!=='0')td.className='error-value';tr.append(td);});rows.append(tr);}$('note-rows').replaceChildren(rows);drawPreview();updateDownload();}
function updateDownload(){$('download').disabled=!(plan&&plan.canExport&&$('ack').checked);}
function download(data,name,mime){const url=URL.createObjectURL(new Blob([data],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('download').addEventListener('click',()=>{if(!plan||!plan.canExport||!$('ack').checked)return;try{const output=C.exportPlan(plan,{acknowledged:true});download(output,plan.direction==='xpt-midi'?'pattern-ferry.mid':'pattern-ferry.xpt',plan.direction==='xpt-midi'?'audio/midi':'application/xml');$('status').textContent=text('変換ファイルを書き出しました。読み込み元は変更していません','Converted file exported. The source file was not changed.');}catch(error){showError(error);}});
$('report').addEventListener('click',()=>{if(!plan)return;const report={product:'PatternFerry',version:'experimental LMMS 1.3.0-alpha.2',audioEquivalence:false,sourceFile:currentName,direction:plan.direction,rounding:plan.rounding,canExport:plan.canExport,acknowledged:$('ack').checked,inputPpqn:plan.inputPpqn,outputPpqn:48,lengthExact:plan.lengthExact,lengthOutput:plan.clip.length,lengthError:plan.lengthError,rows:plan.rows,context:plan.context,metadataNotTransferred:plan.meta,blocked:plan.blocked};download(JSON.stringify(report,null,2)+'\n','pattern-ferry-review.json','application/json');});
$('print').addEventListener('click',()=>{if(plan)window.print();});$('ack').addEventListener('change',updateDownload);
$('file-input').addEventListener('change',event=>{const file=event.target.files[0];event.target.value='';loadFile(file);});
$('reset').addEventListener('click',()=>{revision++;currentBytes=null;currentName='';$('file-input').value='';$('file-summary').hidden=true;clearResult();$('sample').focus();});
for(const radio of document.querySelectorAll('[name=rounding]'))radio.addEventListener('change',()=>{if(currentBytes)analyze();else{$('ack').checked=false;updateDownload();}});
$('lang-ja').addEventListener('click',()=>setLanguage('ja'));$('lang-en').addEventListener('click',()=>setLanguage('en'));
for(const type of ['dragenter','dragover'])$('dropzone').addEventListener(type,event=>{event.preventDefault();$('dropzone').classList.add('dragging');});
for(const type of ['dragleave','drop'])$('dropzone').addEventListener(type,event=>{event.preventDefault();$('dropzone').classList.remove('dragging');});
$('dropzone').addEventListener('drop',event=>{if(event.dataTransfer.files.length!==1){revision++;currentBytes=null;currentName='';clearResult();$('file-summary').hidden=true;showError({code:'FORMAT',message:'Choose exactly one file'});return;}loadFile(event.dataTransfer.files[0]);});
$('sample').addEventListener('click',()=>{const clip={length:384,notes:[{start:0,key:60,length:48,volume:200},{start:0,key:64,length:48,volume:100},{start:0,key:67,length:48,volume:50},{start:96,key:60,length:24,volume:75},{start:120,key:60,length:24,volume:125},{start:192,key:69,length:48,volume:150}]};loadFile(new File([C.writeXpt(clip)],'sample.xpt',{type:'application/xml'}));});
const printDetails=[];window.addEventListener('beforeprint',()=>{for(const d of document.querySelectorAll('details')){printDetails.push([d,d.open]);d.open=true;}});window.addEventListener('afterprint',()=>{for(const [d,open]of printDetails)d.open=open;printDetails.length=0;});
if(location.protocol==='file:')$('offline-download').hidden=true;
setLanguage('ja');
})();
